# Install command-line tools
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
# install coreutils
# Install some other useful utilities like `sponge`
# install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
# install findutils
# Install GNU `sed`, overwriting the built-in `sed`
# install gnu-sed --default-names
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
# install bash
# install bash-completion

# Install wget with IRI support
install wget --enable-iri

# Install RingoJS and Narwhal
# Note that the order in which these are installed is important; see http://git.io/brew-narwhal-ringo.
install ringojs
install narwhal

# Install more recent versions of some OS X tools
# install vim --override-system-vi
install homebrew/dupes/grep
install homebrew/dupes/screen
# install homebrew/php/php55 --with-gmp

# Install Ruby tools
install rbenv
install ruby-build

# Install JS tools
install node # This installs `npm` too using the recommended installation method
install rhino
install phantomjs
install slimerjs

# Install other useful binaries
# install bfg
install git
install imagesnap
install lynx
install pv
install pwgen
install tree
install webkit2png
install xpdf
install ffmpeg

# Install local server stack
install mysql
install dnsmasq

# Install recovery and security tools
install foremost
install nmap
install sqlmap
install hashpump

# Install image utilities
install advancecomp
install apngasm
#install exiv2
install gifsicle
install icoutils
install imagemagick --with-webp
install imageworsener
install jhead
install jpeg
install jpegoptim
install homebrew/headonly/jpegrescan --HEAD
install mozjpeg
install optipng
install perceptualdiff
install pngcrush
install pngnq
install pngquant
install webp
install zopfli --HEAD

# Install CSS and JS compressors
install closure-compiler
install yuicompressor

# Install compression tools
install lbzip2
install p7zip
install pbzip2
install pigz
install pixz
install xz


# Remove outdated versions from the cellar
cleanup
