#!/usr/bin/env bash

# Install GUI applications with Homebrew Cask

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Link Homebrew casks in `/Applications` rather than `~/Applications`
# More configuration options available
# @see https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Install Cask
brew install caskroom/cask/brew-cask
brew tap caskroom/versions
#brew tap caskroom/fonts

# Make sure we're using the latest Cask
brew cask update

# Install GUI applications
brew cask install adapter
brew cask install adobe-creative-cloud
brew cask install airdisplay
brew cask install dropbox
brew cask install firefox
brew cask install firefoxdeveloperedition
brew cask install google-chrome
brew cask install google-chrome-canary
brew cask install imagealpha
brew cask install imageoptim
brew cask install opera
brew cask install opera-beta
brew cask install sequel-pro
brew cask install sublime-text3
brew cask install the-unarchiver
brew cask install totalterminal
brew cask install transmission
brew cask install vlc
brew cask install webkit-nightly
brew cask install xquartz

# Install Virtualization Software
brew cask install vmware-fusion
brew cask install vagrant
brew cask install vagrant-manager

# Install Popcorn Time
brew tap popcorn-time/homebrew-cask https://git.popcorntime.io/caskroom/homebrew-cask.git
brew cask install popcorn-time

# Install Preference Panes
brew cask install hosts

# Install QuickLook Plugins
brew cask install qlcolorcode
brew cask install qlmarkdown
brew cask install qlstephen

# Install Screen Savers
brew cask install ios-lockscreen

# Install Color Picker Plugins
brew cask install colorpicker-developer

# Install others
brew cask install hashcat

# Install non-standard casks
brew tap joeyhoer/homebrew-extras
brew cask install font-microsoft-office

# Remove outdated versions from the cellar
brew cask cleanup
