#!/usr/bin/env bash

# Install GUI applications with Homebrew Cask

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Link Homebrew casks in `/Applications` rather than `~/Applications`
# More configuration options available
# @see https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Install Cask
brew tap caskroom/cask
brew tap caskroom/versions
#brew tap caskroom/fonts

# Make sure we're using the latest Cask
brew update

# Install GUI applications
brew cask install --force adapter
brew cask install --force adobe-creative-cloud
brew cask install --force airdisplay
brew cask install --force airserver
brew cask install --force atom
brew cask install --force bartender
brew cask install --force boom
brew cask install --force colors
brew cask install --force dropbox
brew cask install --force firefox
brew cask install --force firefoxdeveloperedition
brew cask install --force flux
brew cask install --force forklift
brew cask install --force google-chrome
brew cask install --force google-chrome-canary
brew cask install --force imagealpha
brew cask install --force imageoptim
brew cask install --force iterm2-beta
brew cask install --force itsycal
brew cask install --force itsycal
brew cask install --force kaleidoscope
brew cask install --force opera
brew cask install --force opera-beta
brew cask install --force opera-developer
brew cask install --force password-assistant
brew cask install --force safari-technology-preview
brew cask install --force sequel-pro
brew cask install --force sublime-text
brew cask install --force the-unarchiver
brew cask install --force totalterminal
brew cask install --force transmission
brew cask install --force vlc
brew cask install --force webkit-nightly
brew cask install --force wkhtmltopdf
brew cask install --force xquartz

# Install Virtualization Software
brew cask install --force vmware-fusion
brew cask install --force vagrant
brew cask install --force vagrant-manager

# Install Preference Panes
brew cask install --force hosts

# Install QuickLook Plugins
brew cask install --force qlcolorcode
brew cask install --force qlmarkdown
brew cask install --force qlstephen
brew cask install --force webpquicklook

# Install Screen Savers
brew cask install --force ios-lockscreen

# Install Color Picker Plugins
brew cask install --force colorpicker-skalacolor

# Install non-standard casks
brew tap joeyhoer/homebrew-extras
brew cask install --force vector-magic
brew cask install --force font-microsoft-office
brew cask install --force font-san-francisco-compact
brew cask install --force font-san-francisco-ui

# Remove outdated versions from the cellar
brew cask cleanup
